spring:
  profiles:
    active: dev
  application:
    name: 项目名称
mybatis:
  mapper-locations: classpath:mappers/*/*.xml
  type-aliases-package: com.cbkj.electronic_medical_record.beans #实体类所在的包
  config-location: classpath:/mybatis-config.xml

pagehelper:
  helper-dialect: mysql
  reasonable: true
  support-methods-arguments: true

---
server:
  port: 8030
spring:
  profiles: dev
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: sayschi_2347
    url: jdbc:mysql://ip:端口/cbkj_medical_history_dev?useUnicode=true&characterEncoding=UTF-8&useSSL=false&serverTimezone=Asia/Shanghai&allowMultiQueries=true
    max_allowed_packet : 1024M
  redis:
    host: ip
    port: 端口
    password: xxxxx
    database: 1
---
server:
  port: 8031
  servlet:
    context-path: /tcm-cmot/api
#    context-path: /prescription
spring:
  profiles: test
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: sayschi_2347
    url: jdbc:mysql://ip:端口/cbkj_medical_history_dev?useUnicode=true&characterEncoding=UTF-8&useSSL=false&serverTimezone=Asia/Shanghai&allowMultiQueries=true
    max_allowed_packet : 1024M
  redis:
    host: ip
    port: 端口
    password: xxxxx
    database: 1


---

spring:
  profiles:  prod
  datasource:
    primary:
      type: com.alibaba.druid.pool.DruidDataSource
      driver-class-name: com.mysql.cj.jdbc.Driver
      username: 7Pj1sa/0j+l/Jmxbv7plGA==
      password: ZDTcvGOuwsDdDMMo+EGIjVbpWeZJkymN
      url: jdbc:mysql://ip:端口/cbkj_zxyf?useUnicode=true&characterEncoding=UTF-8&useSSL=false&serverTimezone=Asia/Shanghai&allowMultiQueries=true
  redis:
    host: ip
    port: 端口
    password: xxxxx
    database: 1


